//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebWCFConverTemps.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalles", Namespace="http://schemas.datacontract.org/2004/07/ServiceConverTemp")]
    [System.SerializableAttribute()]
    public partial class Detalles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GradosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiteralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SonCentigradosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Grados {
            get {
                return this.GradosField;
            }
            set {
                if ((this.GradosField.Equals(value) != true)) {
                    this.GradosField = value;
                    this.RaisePropertyChanged("Grados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Literal {
            get {
                return this.LiteralField;
            }
            set {
                if ((object.ReferenceEquals(this.LiteralField, value) != true)) {
                    this.LiteralField = value;
                    this.RaisePropertyChanged("Literal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SonCentigrados {
            get {
                return this.SonCentigradosField;
            }
            set {
                if ((this.SonCentigradosField.Equals(value) != true)) {
                    this.SonCentigradosField = value;
                    this.RaisePropertyChanged("SonCentigrados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServWebWCFConverTemps")]
    public interface IServWebWCFConverTemps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServWebWCFConverTemps/ConvCentAFahr", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ConvCentAFahrResponse")]
        double ConvCentAFahr(double gCent);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServWebWCFConverTemps/ConvCentAFahr", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ConvCentAFahrResponse")]
        System.IAsyncResult BeginConvCentAFahr(double gCent, System.AsyncCallback callback, object asyncState);
        
        double EndConvCentAFahr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServWebWCFConverTemps/ConvFahrACent", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ConvFahrACentResponse")]
        double ConvFahrACent(double gFahr);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServWebWCFConverTemps/ConvFahrACent", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ConvFahrACentResponse")]
        System.IAsyncResult BeginConvFahrACent(double gFahr, System.AsyncCallback callback, object asyncState);
        
        double EndConvFahrACent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServWebWCFConverTemps/ResultadoDetallado", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ResultadoDetalladoResponse")]
        ClienteWebWCFConverTemps.ServiceReference1.Detalles ResultadoDetallado(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServWebWCFConverTemps/ResultadoDetallado", ReplyAction="http://tempuri.org/IServWebWCFConverTemps/ResultadoDetalladoResponse")]
        System.IAsyncResult BeginResultadoDetallado(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle, System.AsyncCallback callback, object asyncState);
        
        ClienteWebWCFConverTemps.ServiceReference1.Detalles EndResultadoDetallado(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServWebWCFConverTempsChannel : ClienteWebWCFConverTemps.ServiceReference1.IServWebWCFConverTemps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvCentAFahrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConvCentAFahrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvFahrACentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConvFahrACentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultadoDetalladoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResultadoDetalladoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClienteWebWCFConverTemps.ServiceReference1.Detalles Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClienteWebWCFConverTemps.ServiceReference1.Detalles)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServWebWCFConverTempsClient : System.ServiceModel.ClientBase<ClienteWebWCFConverTemps.ServiceReference1.IServWebWCFConverTemps>, ClienteWebWCFConverTemps.ServiceReference1.IServWebWCFConverTemps {
        
        private BeginOperationDelegate onBeginConvCentAFahrDelegate;
        
        private EndOperationDelegate onEndConvCentAFahrDelegate;
        
        private System.Threading.SendOrPostCallback onConvCentAFahrCompletedDelegate;
        
        private BeginOperationDelegate onBeginConvFahrACentDelegate;
        
        private EndOperationDelegate onEndConvFahrACentDelegate;
        
        private System.Threading.SendOrPostCallback onConvFahrACentCompletedDelegate;
        
        private BeginOperationDelegate onBeginResultadoDetalladoDelegate;
        
        private EndOperationDelegate onEndResultadoDetalladoDelegate;
        
        private System.Threading.SendOrPostCallback onResultadoDetalladoCompletedDelegate;
        
        public ServWebWCFConverTempsClient() {
        }
        
        public ServWebWCFConverTempsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServWebWCFConverTempsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServWebWCFConverTempsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServWebWCFConverTempsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ConvCentAFahrCompletedEventArgs> ConvCentAFahrCompleted;
        
        public event System.EventHandler<ConvFahrACentCompletedEventArgs> ConvFahrACentCompleted;
        
        public event System.EventHandler<ResultadoDetalladoCompletedEventArgs> ResultadoDetalladoCompleted;
        
        public double ConvCentAFahr(double gCent) {
            return base.Channel.ConvCentAFahr(gCent);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConvCentAFahr(double gCent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConvCentAFahr(gCent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndConvCentAFahr(System.IAsyncResult result) {
            return base.Channel.EndConvCentAFahr(result);
        }
        
        private System.IAsyncResult OnBeginConvCentAFahr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double gCent = ((double)(inValues[0]));
            return this.BeginConvCentAFahr(gCent, callback, asyncState);
        }
        
        private object[] OnEndConvCentAFahr(System.IAsyncResult result) {
            double retVal = this.EndConvCentAFahr(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConvCentAFahrCompleted(object state) {
            if ((this.ConvCentAFahrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConvCentAFahrCompleted(this, new ConvCentAFahrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConvCentAFahrAsync(double gCent) {
            this.ConvCentAFahrAsync(gCent, null);
        }
        
        public void ConvCentAFahrAsync(double gCent, object userState) {
            if ((this.onBeginConvCentAFahrDelegate == null)) {
                this.onBeginConvCentAFahrDelegate = new BeginOperationDelegate(this.OnBeginConvCentAFahr);
            }
            if ((this.onEndConvCentAFahrDelegate == null)) {
                this.onEndConvCentAFahrDelegate = new EndOperationDelegate(this.OnEndConvCentAFahr);
            }
            if ((this.onConvCentAFahrCompletedDelegate == null)) {
                this.onConvCentAFahrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConvCentAFahrCompleted);
            }
            base.InvokeAsync(this.onBeginConvCentAFahrDelegate, new object[] {
                        gCent}, this.onEndConvCentAFahrDelegate, this.onConvCentAFahrCompletedDelegate, userState);
        }
        
        public double ConvFahrACent(double gFahr) {
            return base.Channel.ConvFahrACent(gFahr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConvFahrACent(double gFahr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConvFahrACent(gFahr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndConvFahrACent(System.IAsyncResult result) {
            return base.Channel.EndConvFahrACent(result);
        }
        
        private System.IAsyncResult OnBeginConvFahrACent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double gFahr = ((double)(inValues[0]));
            return this.BeginConvFahrACent(gFahr, callback, asyncState);
        }
        
        private object[] OnEndConvFahrACent(System.IAsyncResult result) {
            double retVal = this.EndConvFahrACent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConvFahrACentCompleted(object state) {
            if ((this.ConvFahrACentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConvFahrACentCompleted(this, new ConvFahrACentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConvFahrACentAsync(double gFahr) {
            this.ConvFahrACentAsync(gFahr, null);
        }
        
        public void ConvFahrACentAsync(double gFahr, object userState) {
            if ((this.onBeginConvFahrACentDelegate == null)) {
                this.onBeginConvFahrACentDelegate = new BeginOperationDelegate(this.OnBeginConvFahrACent);
            }
            if ((this.onEndConvFahrACentDelegate == null)) {
                this.onEndConvFahrACentDelegate = new EndOperationDelegate(this.OnEndConvFahrACent);
            }
            if ((this.onConvFahrACentCompletedDelegate == null)) {
                this.onConvFahrACentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConvFahrACentCompleted);
            }
            base.InvokeAsync(this.onBeginConvFahrACentDelegate, new object[] {
                        gFahr}, this.onEndConvFahrACentDelegate, this.onConvFahrACentCompletedDelegate, userState);
        }
        
        public ClienteWebWCFConverTemps.ServiceReference1.Detalles ResultadoDetallado(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle) {
            return base.Channel.ResultadoDetallado(detalle);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginResultadoDetallado(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResultadoDetallado(detalle, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClienteWebWCFConverTemps.ServiceReference1.Detalles EndResultadoDetallado(System.IAsyncResult result) {
            return base.Channel.EndResultadoDetallado(result);
        }
        
        private System.IAsyncResult OnBeginResultadoDetallado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle = ((ClienteWebWCFConverTemps.ServiceReference1.Detalles)(inValues[0]));
            return this.BeginResultadoDetallado(detalle, callback, asyncState);
        }
        
        private object[] OnEndResultadoDetallado(System.IAsyncResult result) {
            ClienteWebWCFConverTemps.ServiceReference1.Detalles retVal = this.EndResultadoDetallado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResultadoDetalladoCompleted(object state) {
            if ((this.ResultadoDetalladoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResultadoDetalladoCompleted(this, new ResultadoDetalladoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResultadoDetalladoAsync(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle) {
            this.ResultadoDetalladoAsync(detalle, null);
        }
        
        public void ResultadoDetalladoAsync(ClienteWebWCFConverTemps.ServiceReference1.Detalles detalle, object userState) {
            if ((this.onBeginResultadoDetalladoDelegate == null)) {
                this.onBeginResultadoDetalladoDelegate = new BeginOperationDelegate(this.OnBeginResultadoDetallado);
            }
            if ((this.onEndResultadoDetalladoDelegate == null)) {
                this.onEndResultadoDetalladoDelegate = new EndOperationDelegate(this.OnEndResultadoDetallado);
            }
            if ((this.onResultadoDetalladoCompletedDelegate == null)) {
                this.onResultadoDetalladoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResultadoDetalladoCompleted);
            }
            base.InvokeAsync(this.onBeginResultadoDetalladoDelegate, new object[] {
                        detalle}, this.onEndResultadoDetalladoDelegate, this.onResultadoDetalladoCompletedDelegate, userState);
        }
    }
}
